server:
  port: 8040 # Server port, you can change this to any other port as required

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true # Enables H2 console for in-browser access
      path: /h2-console # URL path for the H2 console

  jpa:
    hibernate:
      ddl-auto: update # Automatically create and update tables based on entities
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true # Show SQL queries in the log for debugging

logging:
  level:
    org:
      springframework:
        web: DEBUG # Log level for Spring Web
      hibernate:
        SQL: DEBUG # Log level for Hibernate SQL
        type:
          descriptor:
            sql: TRACE # Log level for Hibernate SQL bindings

# Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs # Path for OpenAPI/Swagger documentation
  swagger-ui:
    path: /swagger-ui.html # Path to access the Swagger UI

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all management endpoints
  endpoint:
    health:
      show-details: always # Show detailed health information